import type { WorkflowEdge, WorkflowNode } from "@/lib/types/workflow";

export type {
  EventNodeData,
  PerspectiveNodeData,
  NarrativeNodeData,
  CharacterTraits,
  CharacterNodeData,
  EventNodeType,
  PerspectiveNodeType,
  NarrativeNodeType,
  CharacterNodeType,
  GroupNodeType,
  WorkflowNode,
  WorkflowEdge,
} from "@/lib/types/workflow";

export const initialNodes: WorkflowNode[] = [
  {
    id: "event-group",
    type: "eventGroup",
    position: { x: 200, y: 20 },
    data: { label: "Plot Cluster", eventGroupId: 1 },
    style: {
      width: 1520,
      height: 220,
      backgroundColor: "transparent",
      border: "none",
      padding: 0,
      boxShadow: "none",
    },
  },
  {
    id: "perspective-group-alfred",
    type: "perspectiveGroup",
    position: { x: 0, y: 360 },
    data: {
      label: "Alfred's Perspective",
      characterName: "Alfred",
    },
    style: {
      width: 1520,
      height: 720,
      backgroundColor: "transparent",
      border: "none",
      padding: 0,
      boxShadow: "none",
    },
  },
  {
    id: "perspective-group-dragon",
    type: "perspectiveGroup",
    position: { x: 1620, y: 360 },
    data: {
      label: "Dragon's Perspective",
      characterName: "Dragon",
    },
    style: {
      width: 1520,
      height: 720,
      backgroundColor: "transparent",
      border: "none",
      padding: 0,
      boxShadow: "none",
    },
  },
  {
    id: "narration-group",
    type: "narrativeGroup",
    position: { x: 820, y: 1200 },
    data: {
      label: "Narrative Cluster",
      narrativeGroupId: 1,
    },
    style: {
      width: 1520,
      height: 420,
      backgroundColor: "transparent",
      border: "none",
      padding: 0,
      boxShadow: "none",
    },
  },
  {
    id: "event-1",
    type: "event",
    position: { x: 20, y: 60 },
    draggable: false,
    data: {
      description:
        "Alfred stares at an old castle painting and imagines himself in a kingdom of knights and fire-breathing beasts.",
      timeline: "Plot 1",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-2",
    type: "event",
    position: { x: 320, y: 60 },
    draggable: false,
    data: {
      description:
        "A dragon descends over the valley, and Alfred flees through the forest while searching for a way to survive.",
      timeline: "Plot 2",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-3",
    type: "event",
    position: { x: 620, y: 60 },
    draggable: false,
    data: {
      description:
        "Alfred dons ancient armor and trains with a sword, choosing to confront the dragon instead of hiding.",
      timeline: "Plot 3",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-4",
    type: "event",
    position: { x: 920, y: 60 },
    draggable: false,
    data: {
      description:
        "At the castle ruins, Alfred battles the dragon in a brutal duel and finally brings it down.",
      timeline: "Plot 4",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-5",
    type: "event",
    position: { x: 1220, y: 60 },
    draggable: false,
    data: {
      description:
        "At sunrise, Alfred stands victorious by the castle, honored as the knight who saved the kingdom.",
      timeline: "Plot 5",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "perspective-alfred-1",
    type: "perspective",
    position: { x: 20, y: 60 },
    draggable: false,
    data: {
      narrator: "Alfred",
      reflection:
        "The afternoon sun makes the dust in our sitting room spin like fairy motes, and I press my nose closer to the yellowed painting above the mantel. My eyes chase the winding stone walls, the banners flapping beside pointed rooftops. I imagine soft grass underfoot and the big iron gate creaking open just for me. With each heartbeat, the old castle pulls me in—closer and closer—until I’m not just little Alfred on the rug. I’m a brave knight with shiny armor (I pat my chest, pretending to clang), my sword ready, every hair tingling for adventure.\n\nMy toes twitch when I spot the painted shadows in the valley. In my mind, they stretch and shift—a hint of a dragon’s tail, a glint of gold eye. I hide behind a painted tree, breath quick and sharp, trying to spot a weakness. If I only had a shield! My Mother calls to tidy up, but I hardly hear her over the shouts of painted villagers. They need me. I press my hand to the rough frame and promise them: I’m coming. No beast will win while I’m their knight.",
      isLoading: false,
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "perspective-alfred-2",
    type: "perspective",
    position: { x: 320, y: 60 },
    draggable: false,
    data: {
      narrator: "Alfred",
      reflection:
        "Branches whipped my face as I crashed through the underbrush, breath rasping in my chest. Every heartbeat thudded against my ribs, urging me onward as the dragon’s shadow crossed the canopy overhead. My shirt snagged on thorns, the fabric tearing, but I barely felt it past the burning in my calves and the raw panic clawing at my mind.\n\nThe smoke stung my eyes, thick and acrid, drifting from the fields behind me—home, swallowed by fire. I gulped down another lungful of smoky air, nearly tripping on a root as I searched the tangled forest for any sign of shelter. Was anyone else left, or had I been the only one fast enough to run? I pressed on, desperate to find a hollow, a rock outcrop, anything. Each roar behind me seemed closer, promising that if I stopped, if I faltered, there would be nothing left. Yet through the terror, something flickered—if I could keep moving, if I could find cover, maybe there was a chance not just to hide, but to find some way to fight for what was left.",
      isLoading: false,
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "perspective-alfred-3",
    type: "perspective",
    position: { x: 620, y: 60 },
    draggable: false,
    data: {
      narrator: "Alfred",
      reflection:
        "The armor sat heavy on my shoulders as I buckled the last strap, its metal scent sharp in the chill light. Each plate whispered with the promise of pain and hope. I looked at my hands—knuckles split, blisters raw, nails rimmed with black where sword hilt met palm. Every moment training in these ruins, chasing the shape of my own fear, had carved me into something different. I was not born a knight, but now, with every swing, I held the future of the valley in my fists.\n\nWhen the castle guard offered their silent nods, trust sparked like flint striking stone. I remembered running—lungs burning, terror wild—yet here I was, standing my ground. The old sword felt right in my grip, its balance learned by bruises and stubborn will. I pictured scales and fire, and instead of retreat, I flexed my grip tighter, pushing terror aside. This is what I am for. To guard, to fight, to choose courage where fear had once reigned. Today, I would face the dragon, not as prey, but as protector.",
      isLoading: false,
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "perspective-alfred-4",
    type: "perspective",
    position: { x: 920, y: 60 },
    draggable: false,
    data: {
      narrator: "Alfred",
      reflection:
        "Steel clanged, sparks spit wild as my blade met dragon-scale. Armor weighed heavy, pressing sharp ridges into my burning shoulders. My breath rasped inside the helmet—thick with sweat, the taste of iron and smoke on my tongue. The dragon’s eyes blazed gold above me, every exhale a furnace, every claw-skid gouging stone. My hands—calloused, trembling—tightened on the hilt, knuckles splitting anew as I forced the sword’s tip beneath a wing, just as it reared.\n\nEvery instinct screamed to run, to flee the heat peeling paint from crumbling walls, but I drove forward, vision tunneling until nothing existed but sparks, blood, and the roar of its rage. Fear was everywhere, threading my ribs tight, yet I found the rhythm I’d earned in lonely hours—step, twist, strike—using the battered shield to turn aside the shredding jaws. One last lunge: blade sliding home beneath scales, the dragon’s cry shaking the stones. Then—silence, its shadow unmoving. Gasping, armor ringing hollow, I staggered upright. Dawn bled over the shattered keep. I stood atop broken stones, breathing hard, knowing the terror and the triumph shimmering together in my bones.",
      isLoading: false,
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "perspective-alfred-5",
    type: "perspective",
    position: { x: 1220, y: 60 },
    draggable: false,
    data: {
      narrator: "Alfred",
      reflection:
        "The first light of dawn glints off my battered breastplate, painting the castle stones gold and rose. My hands ache, fingers wrapped tight around the pommel of the sword that not long ago struck true against the dragon’s scales. My breath still clouds in the morning chill, but I lift my head high. The silence now feels different; it is a peace hard-won, layered over the memory of roars and flame. Villagers fill the ruined courtyard, eyes wide, voices hushed in awe I am not sure I deserve. I meet their gazes with a nod—no grand gestures, just the steady knowledge that I did what duty required. Wind stirs the banners where I stand. Smoke and blood cling faintly to my skin, but beneath it, I feel a strange warmth, pride edged with grateful relief. My legs want to fold with exhaustion, but I lock my knees and smile, because the kingdom needs a guardian who can endure—someone who sees through fear and stands when it matters most. Today, they call me a knight. But more important to me: today, the people are safe.",
      isLoading: false,
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "perspective-dragon-1",
    type: "perspective",
    position: { x: 20, y: 60 },
    draggable: false,
    data: {
      narrator: "Dragon",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "perspective-dragon-2",
    type: "perspective",
    position: { x: 320, y: 60 },
    draggable: false,
    data: {
      narrator: "Dragon",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "perspective-dragon-3",
    type: "perspective",
    position: { x: 620, y: 60 },
    draggable: false,
    data: {
      narrator: "Dragon",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "perspective-dragon-4",
    type: "perspective",
    position: { x: 920, y: 60 },
    draggable: false,
    data: {
      narrator: "Dragon",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "perspective-dragon-5",
    type: "perspective",
    position: { x: 1220, y: 60 },
    draggable: false,
    data: {
      narrator: "Dragon",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "character-alfred-1",
    type: "character",
    position: { x: 20, y: 280 },
    draggable: false,
    data: {
      name: "Alfred",
      traits: {
        physiology: ["Small child", "Bright curious eyes"],
        psychology: ["Imaginative", "Curious", "Easily excited by adventure"],
        sociology: ["Dreamer from the village", "Loves heroic legends"],
      },
      perspectiveId: "perspective-alfred-1",
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "character-alfred-2",
    type: "character",
    position: { x: 320, y: 280 },
    draggable: false,
    data: {
      name: "Alfred",
      traits: {
        physiology: [
          "Breathing hard from sprinting",
          "Clothes torn by brambles",
        ],
        psychology: ["Fearful", "Uncertain", "Desperate to find safety"],
        sociology: [
          "A lone survivor in the valley",
          "Driven to protect his home",
        ],
      },
      perspectiveId: "perspective-alfred-2",
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "character-alfred-3",
    type: "character",
    position: { x: 620, y: 280 },
    draggable: false,
    data: {
      name: "Alfred",
      traits: {
        physiology: [
          "Wears shining knight's armor",
          "Carries a gleaming sword",
          "Calloused hands from intense training",
        ],
        psychology: [
          "Overcomes fear with courage",
          "Ready to fight for what is right",
        ],
        sociology: [
          "Sworn protector of the land",
          "Trusted by the castle guard",
        ],
      },
      perspectiveId: "perspective-alfred-3",
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "character-alfred-4",
    type: "character",
    position: { x: 920, y: 280 },
    draggable: false,
    data: {
      name: "Alfred",
      traits: {
        physiology: [
          "Wears heavy armor",
          "Calloused and trembling hands",
          "Sweating from exertion",
        ],
        psychology: ["Fighting through fear"],
        sociology: ["Knight facing a dragon", "Protector of the kingdom"],
      },
      perspectiveId: "perspective-alfred-4",
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "character-alfred-5",
    type: "character",
    position: { x: 1220, y: 280 },
    draggable: false,
    data: {
      name: "Alfred",
      traits: {
        physiology: ["Stands tall and proud", "Battle-worn but smiling"],
        psychology: [
          "Brave and confident",
          "Humble in victory",
          "Steady under pressure",
        ],
        sociology: ["Hero of the castle", "Guardian of the kingdom"],
      },
      perspectiveId: "perspective-alfred-5",
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "character-dragon-2",
    type: "character",
    position: { x: 320, y: 280 },
    draggable: false,
    data: {
      name: "Dragon",
      traits: {
        physiology: [
          "Enormous scaly beast",
          "Breathes scorching fire",
          "Wings that darken the sky",
        ],
        psychology: [
          "Fearsome and territorial",
          "Driven by hunger and dominance",
          "Unaware of its own loneliness",
        ],
        sociology: ["Terror of the kingdom", "Feared by all villagers"],
      },
      perspectiveId: "perspective-dragon-2",
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "character-dragon-4",
    type: "character",
    position: { x: 920, y: 280 },
    draggable: false,
    data: {
      name: "Dragon",
      traits: {
        physiology: [
          "Scales cracked by sword strikes",
          "Fire faltering after the duel",
        ],
        psychology: [
          "Furious but increasingly desperate",
          "Surprised by Alfred's courage",
          "Fighting with all remaining strength",
        ],
        sociology: [
          "Challenged for the first time",
          "Losing grip on its dominance",
        ],
      },
      perspectiveId: "perspective-dragon-4",
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "character-dragon-5",
    type: "character",
    position: { x: 1220, y: 280 },
    draggable: false,
    data: {
      name: "Dragon",
      traits: {
        physiology: ["Defeated and grounded", "Fire extinguished"],
        psychology: [
          "Humbled by defeat",
          "Beginning to understand respect",
          "No longer driven by rage",
        ],
        sociology: [
          "No longer a threat to the kingdom",
          "A reminder that courage conquers fear",
        ],
      },
      perspectiveId: "perspective-dragon-5",
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "narrative-1",
    type: "narrative",
    position: { x: 20, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
    },
    parentId: "narration-group",
    extent: "parent",
  },
  {
    id: "narrative-2",
    type: "narrative",
    position: { x: 320, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
    },
    parentId: "narration-group",
    extent: "parent",
  },
  {
    id: "narrative-3",
    type: "narrative",
    position: { x: 620, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
    },
    parentId: "narration-group",
    extent: "parent",
  },
  {
    id: "narrative-4",
    type: "narrative",
    position: { x: 920, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
    },
    parentId: "narration-group",
    extent: "parent",
  },
  {
    id: "narrative-5",
    type: "narrative",
    position: { x: 1220, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
    },
    parentId: "narration-group",
    extent: "parent",
  },
];

export const initialEdges: WorkflowEdge[] = [
  {
    id: "edge-event-group-perspective-group-alfred",
    source: "event-group",
    target: "perspective-group-alfred",
    sourceHandle: "group-bridge",
    targetHandle: "group-bridge",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-group-perspective-group-dragon",
    source: "event-group",
    target: "perspective-group-dragon",
    sourceHandle: "group-bridge",
    targetHandle: "group-bridge",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-group-alfred-narration-group",
    source: "perspective-group-alfred",
    target: "narration-group",
    sourceHandle: "narrative-bridge",
    targetHandle: "group-bridge",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-group-dragon-narration-group",
    source: "perspective-group-dragon",
    target: "narration-group",
    sourceHandle: "narrative-bridge",
    targetHandle: "group-bridge",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-1-2",
    source: "event-1",
    target: "event-2",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "eventEdge",
    animated: true,
  },
  {
    id: "edge-event-2-3",
    source: "event-2",
    target: "event-3",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "eventEdge",
    animated: true,
  },
  {
    id: "edge-event-3-4",
    source: "event-3",
    target: "event-4",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "eventEdge",
    animated: true,
  },
  {
    id: "edge-event-4-5",
    source: "event-4",
    target: "event-5",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "eventEdge",
    animated: true,
  },
  {
    id: "edge-perspective-alfred-1-2",
    source: "perspective-alfred-1",
    target: "perspective-alfred-2",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-alfred-2-3",
    source: "perspective-alfred-2",
    target: "perspective-alfred-3",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-alfred-3-4",
    source: "perspective-alfred-3",
    target: "perspective-alfred-4",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-alfred-4-5",
    source: "perspective-alfred-4",
    target: "perspective-alfred-5",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-dragon-1-2",
    source: "perspective-dragon-1",
    target: "perspective-dragon-2",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-dragon-2-3",
    source: "perspective-dragon-2",
    target: "perspective-dragon-3",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-dragon-3-4",
    source: "perspective-dragon-3",
    target: "perspective-dragon-4",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-dragon-4-5",
    source: "perspective-dragon-4",
    target: "perspective-dragon-5",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-alfred-1-perspective-alfred-1",
    source: "character-alfred-1",
    target: "perspective-alfred-1",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-alfred-2-perspective-alfred-2",
    source: "character-alfred-2",
    target: "perspective-alfred-2",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-alfred-3-perspective-alfred-3",
    source: "character-alfred-3",
    target: "perspective-alfred-3",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-alfred-4-perspective-alfred-4",
    source: "character-alfred-4",
    target: "perspective-alfred-4",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-alfred-5-perspective-alfred-5",
    source: "character-alfred-5",
    target: "perspective-alfred-5",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-dragon-2-perspective-dragon-2",
    source: "character-dragon-2",
    target: "perspective-dragon-2",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-dragon-4-perspective-dragon-4",
    source: "character-dragon-4",
    target: "perspective-dragon-4",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-dragon-5-perspective-dragon-5",
    source: "character-dragon-5",
    target: "perspective-dragon-5",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-narrative-1-2",
    source: "narrative-1",
    target: "narrative-2",
    sourceHandle: "narrative-next",
    targetHandle: "narrative-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-narrative-2-3",
    source: "narrative-2",
    target: "narrative-3",
    sourceHandle: "narrative-next",
    targetHandle: "narrative-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-narrative-3-4",
    source: "narrative-3",
    target: "narrative-4",
    sourceHandle: "narrative-next",
    targetHandle: "narrative-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-narrative-4-5",
    source: "narrative-4",
    target: "narrative-5",
    sourceHandle: "narrative-next",
    targetHandle: "narrative-prev",
    type: "customEdge",
    animated: true,
  },
];
