import type { WorkflowEdge, WorkflowNode } from "@/lib/types/workflow";

export type {
  EventNodeData,
  PerspectiveNodeData,
  CharacterTraits,
  CharacterNodeData,
  EventNodeType,
  PerspectiveNodeType,
  CharacterNodeType,
  GroupNodeType,
  WorkflowNode,
  WorkflowEdge,
} from "@/lib/types/workflow";

export const initialNodes: WorkflowNode[] = [
  {
    id: "event-group",
    type: "group",
    position: { x: 100, y: 20 },
    data: { label: "Story Event Plans" },
    style: {
      width: 1200,
      height: 200,
      backgroundColor: "rgba(240, 240, 255, 0.3)",
      border: "2px solid rgba(100, 100, 200, 0.3)",
      borderRadius: "8px",
      padding: "20px",
    },
  },
  {
    id: "event-1",
    type: "event",
    position: { x: 20, y: 40 },
    draggable: false,
    data: {
      description:
        "At dawn, a band of raiders torches the outer granary; Aria breaks formation to drag a trapped child to safety while the rest hold the line.",
      timeline: "Event 1",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-2",
    type: "event",
    position: { x: 320, y: 40 },
    draggable: false,
    data: {
      description:
        "That afternoon, the council publicly reprimands Aria and demotes her to archive duty, placing her under the watch of the cautious historian Lysa.",
      timeline: "Event 2",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-3",
    type: "event",
    position: { x: 620, y: 40 },
    draggable: false,
    data: {
      description:
        "Night falls and the raiders return; drawing on what she learned in the archives, Aria coordinates an ambush that routes the attackers without further loss.",
      timeline: "Event 3",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-4",
    type: "event",
    position: { x: 920, y: 40 },
    draggable: false,
    data: {
      description:
        "At week's end, Aria and Lysa present the ambush tactics to the council, earning a mandate to train scouts and archivists together.",
      timeline: "Event 4",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "perspective-1",
    type: "perspective",
    position: { x: 120, y: 240 },
    draggable: false,
    data: {
      narrator: "Aria",
      reflection: "",
      isLoading: false,
    },
  },
  {
    id: "perspective-2",
    type: "perspective",
    position: { x: 420, y: 240 },
    draggable: false,
    data: {
      narrator: "Aria",
      reflection: "",
      isLoading: false,
    },
  },
  {
    id: "perspective-3",
    type: "perspective",
    position: { x: 720, y: 240 },
    draggable: false,
    data: {
      narrator: "Aria",
      reflection: "",
      isLoading: false,
    },
  },
  {
    id: "perspective-4",
    type: "perspective",
    position: { x: 1020, y: 240 },
    draggable: false,
    data: {
      narrator: "Aria",
      reflection: "",
      isLoading: false,
    },
  },
  {
    id: "character-start",
    type: "character",
    position: { x: 120, y: 450 },
    data: {
      name: "Aria",
      traits: {
        physiology: ["Quick-footed scout"],
        psychology: ["Impulsive", "Hungry to prove herself"],
        sociology: [
          "Favored by the village guard captain",
          "Resented by the archive scribes",
        ],
      },
    },
  },
  {
    id: "character-end",
    type: "character",
    position: { x: 1020, y: 450 },
    data: {
      name: "Aria",
      traits: {
        physiology: ["Wears a reinforced archivist's cloak"],
        psychology: ["Strategic", "Protective without recklessness"],
        sociology: ["Accepted voice on the village council"],
      },
    },
  },
];

export const initialEdges: WorkflowEdge[] = [
  {
    id: "edge-event-1-2",
    source: "event-1",
    target: "event-2",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-2-3",
    source: "event-2",
    target: "event-3",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-3-4",
    source: "event-3",
    target: "event-4",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-1-perspective-1",
    source: "event-1",
    target: "perspective-1",
    sourceHandle: "perspective",
    targetHandle: "event",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-2-perspective-2",
    source: "event-2",
    target: "perspective-2",
    sourceHandle: "perspective",
    targetHandle: "event",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-3-perspective-3",
    source: "event-3",
    target: "perspective-3",
    sourceHandle: "perspective",
    targetHandle: "event",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-4-perspective-4",
    source: "event-4",
    target: "perspective-4",
    sourceHandle: "perspective",
    targetHandle: "event",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-1-2",
    source: "perspective-1",
    target: "perspective-2",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-2-3",
    source: "perspective-2",
    target: "perspective-3",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-3-4",
    source: "perspective-3",
    target: "perspective-4",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-start-perspective-1",
    source: "character-start",
    target: "perspective-1",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-end-perspective-4",
    source: "character-end",
    target: "perspective-4",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
];
