import type { WorkflowEdge, WorkflowNode } from "@/lib/types/workflow";

export type {
  EventNodeData,
  PerspectiveNodeData,
  NarrativeNodeData,
  CharacterTraits,
  CharacterNodeData,
  EventNodeType,
  PerspectiveNodeType,
  NarrativeNodeType,
  CharacterNodeType,
  GroupNodeType,
  WorkflowNode,
  WorkflowEdge,
} from "@/lib/types/workflow";

export const initialNodes: WorkflowNode[] = [
  {
    id: "event-group",
    type: "eventGroup",
    position: { x: 200, y: 20 },
    data: { label: "Story Outline" },
    style: {
      width: 1200,
      height: 220,
      backgroundColor: "transparent",
      border: "none",
      padding: 0,
      boxShadow: "none",
    },
  },
  {
    id: "perspective-group",
    type: "perspectiveGroup",
    position: { x: 0, y: 320 },
    data: {
      label: "First-Person Limited Cluster",
      characterName: "Aria",
    },
    style: {
      width: 1200,
      height: 640,
      backgroundColor: "transparent",
      border: "none",
      padding: 0,
      boxShadow: "none",
    },
  },
  {
    id: "narration-group",
    type: "narrativeGroup",
    position: { x: 200, y: 1100 },
    data: {
      label: "Third-Person Omniscient Cluster",
    },
    style: {
      width: 1200,
      height: 300,
      backgroundColor: "transparent",
      border: "none",
      padding: 0,
      boxShadow: "none",
    },
  },
  {
    id: "event-1",
    type: "event",
    position: { x: 20, y: 60 },
    draggable: false,
    data: {
      description:
        "At dawn, a band of raiders torches the outer granary; Aria breaks formation to drag a trapped child to safety while the rest hold the line.",
      timeline: "Event 1",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-2",
    type: "event",
    position: { x: 320, y: 60 },
    draggable: false,
    data: {
      description:
        "That afternoon, the council publicly reprimands Aria and demotes her to archive duty, placing her under the watch of the cautious historian Lysa.",
      timeline: "Event 2",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-3",
    type: "event",
    position: { x: 620, y: 60 },
    draggable: false,
    data: {
      description:
        "Night falls and the raiders return; drawing on what she learned in the archives, Aria coordinates an ambush that routes the attackers without further loss.",
      timeline: "Event 3",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-4",
    type: "event",
    position: { x: 920, y: 60 },
    draggable: false,
    data: {
      description:
        "At week's end, Aria and Lysa present the ambush tactics to the council, earning a mandate to train scouts and archivists together.",
      timeline: "Event 4",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "perspective-1",
    type: "perspective",
    position: { x: 20, y: 60 },
    draggable: false,
    data: {
      narrator: "Aria",
      reflection: "",
      isLoading: false,
      eventId: "event-1",
    },
    parentId: "perspective-group",
    extent: "parent",
  },
  {
    id: "perspective-2",
    type: "perspective",
    position: { x: 320, y: 60 },
    draggable: false,
    data: {
      narrator: "Aria",
      reflection: "",
      isLoading: false,
      eventId: "event-2",
    },
    parentId: "perspective-group",
    extent: "parent",
  },
  {
    id: "perspective-3",
    type: "perspective",
    position: { x: 620, y: 60 },
    draggable: false,
    data: {
      narrator: "Aria",
      reflection: "",
      isLoading: false,
      eventId: "event-3",
    },
    parentId: "perspective-group",
    extent: "parent",
  },
  {
    id: "perspective-4",
    type: "perspective",
    position: { x: 920, y: 60 },
    draggable: false,
    data: {
      narrator: "Aria",
      reflection: "",
      isLoading: false,
      eventId: "event-4",
    },
    parentId: "perspective-group",
    extent: "parent",
  },
  {
    id: "character-1",
    type: "character",
    position: { x: 20, y: 280 },
    draggable: false,
    data: {
      name: "Aria",
      traits: {
        physiology: ["Quick-footed scout"],
        psychology: ["Impulsive", "Hungry to prove herself"],
        sociology: [
          "Favored by the village guard captain",
          "Resented by the archive scribes",
        ],
      },
      perspectiveId: "perspective-1",
    },
    parentId: "perspective-group",
    extent: "parent",
  },
  {
    id: "character-2",
    type: "character",
    position: { x: 920, y: 280 },
    draggable: false,
    data: {
      name: "Aria",
      traits: {
        physiology: ["Wears a reinforced archivist's cloak"],
        psychology: ["Strategic", "Protective without recklessness"],
        sociology: ["Accepted voice on the village council"],
      },
      perspectiveId: "perspective-4",
    },
    parentId: "perspective-group",
    extent: "parent",
  },
  {
    id: "narrative-1",
    type: "narrative",
    position: { x: 20, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
      eventId: "event-1",
    },
    parentId: "narration-group",
    extent: "parent",
  },
  {
    id: "narrative-2",
    type: "narrative",
    position: { x: 320, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
      eventId: "event-2",
    },
    parentId: "narration-group",
    extent: "parent",
  },
  {
    id: "narrative-3",
    type: "narrative",
    position: { x: 620, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
      eventId: "event-3",
    },
    parentId: "narration-group",
    extent: "parent",
  },
  {
    id: "narrative-4",
    type: "narrative",
    position: { x: 920, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
      eventId: "event-4",
    },
    parentId: "narration-group",
    extent: "parent",
  },
];

export const initialEdges: WorkflowEdge[] = [
  {
    id: "edge-event-group-perspective-group",
    source: "event-group",
    target: "perspective-group",
    sourceHandle: "group-bridge",
    targetHandle: "group-bridge",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-1-2",
    source: "event-1",
    target: "event-2",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-2-3",
    source: "event-2",
    target: "event-3",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-3-4",
    source: "event-3",
    target: "event-4",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-1-2",
    source: "perspective-1",
    target: "perspective-2",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-2-3",
    source: "perspective-2",
    target: "perspective-3",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-3-4",
    source: "perspective-3",
    target: "perspective-4",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-1-perspective-1",
    source: "character-1",
    target: "perspective-1",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-2-perspective-4",
    source: "character-2",
    target: "perspective-4",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-narrative-1-2",
    source: "narrative-1",
    target: "narrative-2",
    sourceHandle: "narrative-next",
    targetHandle: "narrative-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-narrative-2-3",
    source: "narrative-2",
    target: "narrative-3",
    sourceHandle: "narrative-next",
    targetHandle: "narrative-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-narrative-3-4",
    source: "narrative-3",
    target: "narrative-4",
    sourceHandle: "narrative-next",
    targetHandle: "narrative-prev",
    type: "customEdge",
    animated: true,
  },
];
