import type { WorkflowEdge, WorkflowNode } from "@/lib/types/workflow";

export type {
  EventNodeData,
  PerspectiveNodeData,
  NarrativeNodeData,
  CharacterTraits,
  CharacterNodeData,
  EventNodeType,
  PerspectiveNodeType,
  NarrativeNodeType,
  CharacterNodeType,
  GroupNodeType,
  WorkflowNode,
  WorkflowEdge,
} from "@/lib/types/workflow";

export const initialNodes: WorkflowNode[] = [
  {
    id: "event-group",
    type: "eventGroup",
    position: { x: 200, y: 20 },
    data: { label: "Plot Cluster", eventGroupId: 1 },
    style: {
      width: 1520,
      height: 220,
      backgroundColor: "transparent",
      border: "none",
      padding: 0,
      boxShadow: "none",
    },
  },
  {
    id: "perspective-group-alfred",
    type: "perspectiveGroup",
    position: { x: 0, y: 360 },
    data: {
      label: "Alfred's Perspective",
      characterName: "Alfred",
    },
    style: {
      width: 1520,
      height: 720,
      backgroundColor: "transparent",
      border: "none",
      padding: 0,
      boxShadow: "none",
    },
  },
  {
    id: "perspective-group-dragon",
    type: "perspectiveGroup",
    position: { x: 1620, y: 360 },
    data: {
      label: "Dragon's Perspective",
      characterName: "Dragon",
    },
    style: {
      width: 1520,
      height: 720,
      backgroundColor: "transparent",
      border: "none",
      padding: 0,
      boxShadow: "none",
    },
  },
  {
    id: "narration-group",
    type: "narrativeGroup",
    position: { x: 820, y: 1200 },
    data: {
      label: "Narrative Cluster",
      narrativeGroupId: 1,
    },
    style: {
      width: 1520,
      height: 420,
      backgroundColor: "transparent",
      border: "none",
      padding: 0,
      boxShadow: "none",
    },
  },
  {
    id: "event-1",
    type: "event",
    position: { x: 20, y: 60 },
    draggable: false,
    data: {
      description:
        "Alfred stares at an old castle painting and imagines himself in a kingdom of knights and fire-breathing beasts.",
      timeline: "Plot 1",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-2",
    type: "event",
    position: { x: 320, y: 60 },
    draggable: false,
    data: {
      description:
        "A dragon descends over the valley, and Alfred flees through the forest while searching for a way to survive.",
      timeline: "Plot 2",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-3",
    type: "event",
    position: { x: 620, y: 60 },
    draggable: false,
    data: {
      description:
        "Alfred dons ancient armor and trains with a sword, choosing to confront the dragon instead of hiding.",
      timeline: "Plot 3",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-4",
    type: "event",
    position: { x: 920, y: 60 },
    draggable: false,
    data: {
      description:
        "At the castle ruins, Alfred battles the dragon in a brutal duel and finally brings it down.",
      timeline: "Plot 4",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "event-5",
    type: "event",
    position: { x: 1220, y: 60 },
    draggable: false,
    data: {
      description:
        "At sunrise, Alfred stands victorious by the castle, honored as the knight who saved the kingdom.",
      timeline: "Plot 5",
    },
    parentId: "event-group",
    extent: "parent",
  },
  {
    id: "perspective-alfred-1",
    type: "perspective",
    position: { x: 20, y: 60 },
    draggable: false,
    data: {
      narrator: "Alfred",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "perspective-alfred-2",
    type: "perspective",
    position: { x: 320, y: 60 },
    draggable: false,
    data: {
      narrator: "Alfred",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "perspective-alfred-3",
    type: "perspective",
    position: { x: 620, y: 60 },
    draggable: false,
    data: {
      narrator: "Alfred",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "perspective-alfred-4",
    type: "perspective",
    position: { x: 920, y: 60 },
    draggable: false,
    data: {
      narrator: "Alfred",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "perspective-alfred-5",
    type: "perspective",
    position: { x: 1220, y: 60 },
    draggable: false,
    data: {
      narrator: "Alfred",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "perspective-dragon-1",
    type: "perspective",
    position: { x: 20, y: 60 },
    draggable: false,
    data: {
      narrator: "Dragon",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "perspective-dragon-2",
    type: "perspective",
    position: { x: 320, y: 60 },
    draggable: false,
    data: {
      narrator: "Dragon",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "perspective-dragon-3",
    type: "perspective",
    position: { x: 620, y: 60 },
    draggable: false,
    data: {
      narrator: "Dragon",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "perspective-dragon-4",
    type: "perspective",
    position: { x: 920, y: 60 },
    draggable: false,
    data: {
      narrator: "Dragon",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "perspective-dragon-5",
    type: "perspective",
    position: { x: 1220, y: 60 },
    draggable: false,
    data: {
      narrator: "Dragon",
      reflection: "",
      isLoading: false,
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "character-alfred-1",
    type: "character",
    position: { x: 20, y: 280 },
    draggable: false,
    data: {
      name: "Alfred",
      traits: {
        physiology: ["Small child", "Bright curious eyes"],
        psychology: ["Imaginative", "Curious", "Easily excited by adventure"],
        sociology: ["Dreamer from the village", "Loves heroic legends"],
      },
      perspectiveId: "perspective-alfred-1",
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "character-alfred-2",
    type: "character",
    position: { x: 320, y: 280 },
    draggable: false,
    data: {
      name: "Alfred",
      traits: {
        physiology: [
          "Breathing hard from sprinting",
          "Clothes torn by brambles",
        ],
        psychology: ["Fearful", "Uncertain", "Desperate to find safety"],
        sociology: [
          "A lone survivor in the valley",
          "Driven to protect his home",
        ],
      },
      perspectiveId: "perspective-alfred-2",
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "character-alfred-3",
    type: "character",
    position: { x: 620, y: 280 },
    draggable: false,
    data: {
      name: "Alfred",
      traits: {
        physiology: [
          "Wears shining knight's armor",
          "Carries a gleaming sword",
        ],
        psychology: [
          "Determined to protect others",
          "Overcomes fear with courage",
          "Ready to fight for what is right",
        ],
        sociology: [
          "Sworn protector of the land",
          "Trusted by the castle guard",
        ],
      },
      perspectiveId: "perspective-alfred-3",
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "character-alfred-5",
    type: "character",
    position: { x: 1220, y: 280 },
    draggable: false,
    data: {
      name: "Alfred",
      traits: {
        physiology: ["Stands tall and proud", "Battle-worn but smiling"],
        psychology: [
          "Brave and confident",
          "Humble in victory",
          "Steady under pressure",
        ],
        sociology: ["Hero of the castle", "Guardian of the kingdom"],
      },
      perspectiveId: "perspective-alfred-5",
    },
    parentId: "perspective-group-alfred",
    extent: "parent",
  },
  {
    id: "character-dragon-2",
    type: "character",
    position: { x: 320, y: 280 },
    draggable: false,
    data: {
      name: "Dragon",
      traits: {
        physiology: [
          "Enormous scaly beast",
          "Breathes scorching fire",
          "Wings that darken the sky",
        ],
        psychology: [
          "Fearsome and territorial",
          "Driven by hunger and dominance",
          "Unaware of its own loneliness",
        ],
        sociology: ["Terror of the kingdom", "Feared by all villagers"],
      },
      perspectiveId: "perspective-dragon-2",
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "character-dragon-4",
    type: "character",
    position: { x: 920, y: 280 },
    draggable: false,
    data: {
      name: "Dragon",
      traits: {
        physiology: [
          "Scales cracked by sword strikes",
          "Fire faltering after the duel",
        ],
        psychology: [
          "Furious but increasingly desperate",
          "Surprised by Alfred's courage",
          "Fighting with all remaining strength",
        ],
        sociology: [
          "Challenged for the first time",
          "Losing grip on its dominance",
        ],
      },
      perspectiveId: "perspective-dragon-4",
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "character-dragon-5",
    type: "character",
    position: { x: 1220, y: 280 },
    draggable: false,
    data: {
      name: "Dragon",
      traits: {
        physiology: ["Defeated and grounded", "Fire extinguished"],
        psychology: [
          "Humbled by defeat",
          "Beginning to understand respect",
          "No longer driven by rage",
        ],
        sociology: [
          "No longer a threat to the kingdom",
          "A reminder that courage conquers fear",
        ],
      },
      perspectiveId: "perspective-dragon-5",
    },
    parentId: "perspective-group-dragon",
    extent: "parent",
  },
  {
    id: "narrative-1",
    type: "narrative",
    position: { x: 20, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
    },
    parentId: "narration-group",
    extent: "parent",
  },
  {
    id: "narrative-2",
    type: "narrative",
    position: { x: 320, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
    },
    parentId: "narration-group",
    extent: "parent",
  },
  {
    id: "narrative-3",
    type: "narrative",
    position: { x: 620, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
    },
    parentId: "narration-group",
    extent: "parent",
  },
  {
    id: "narrative-4",
    type: "narrative",
    position: { x: 920, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
    },
    parentId: "narration-group",
    extent: "parent",
  },
  {
    id: "narrative-5",
    type: "narrative",
    position: { x: 1220, y: 60 },
    draggable: false,
    data: {
      narration: "",
      isLoading: false,
    },
    parentId: "narration-group",
    extent: "parent",
  },
];

export const initialEdges: WorkflowEdge[] = [
  {
    id: "edge-event-group-perspective-group-alfred",
    source: "event-group",
    target: "perspective-group-alfred",
    sourceHandle: "group-bridge",
    targetHandle: "group-bridge",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-group-perspective-group-dragon",
    source: "event-group",
    target: "perspective-group-dragon",
    sourceHandle: "group-bridge",
    targetHandle: "group-bridge",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-group-alfred-narration-group",
    source: "perspective-group-alfred",
    target: "narration-group",
    sourceHandle: "narrative-bridge",
    targetHandle: "group-bridge",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-group-dragon-narration-group",
    source: "perspective-group-dragon",
    target: "narration-group",
    sourceHandle: "narrative-bridge",
    targetHandle: "group-bridge",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-event-1-2",
    source: "event-1",
    target: "event-2",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "eventEdge",
    animated: true,
  },
  {
    id: "edge-event-2-3",
    source: "event-2",
    target: "event-3",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "eventEdge",
    animated: true,
  },
  {
    id: "edge-event-3-4",
    source: "event-3",
    target: "event-4",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "eventEdge",
    animated: true,
  },
  {
    id: "edge-event-4-5",
    source: "event-4",
    target: "event-5",
    sourceHandle: "event-next",
    targetHandle: "event-prev",
    type: "eventEdge",
    animated: true,
  },
  {
    id: "edge-perspective-alfred-1-2",
    source: "perspective-alfred-1",
    target: "perspective-alfred-2",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-alfred-2-3",
    source: "perspective-alfred-2",
    target: "perspective-alfred-3",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-alfred-3-4",
    source: "perspective-alfred-3",
    target: "perspective-alfred-4",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-alfred-4-5",
    source: "perspective-alfred-4",
    target: "perspective-alfred-5",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-dragon-1-2",
    source: "perspective-dragon-1",
    target: "perspective-dragon-2",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-dragon-2-3",
    source: "perspective-dragon-2",
    target: "perspective-dragon-3",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-dragon-3-4",
    source: "perspective-dragon-3",
    target: "perspective-dragon-4",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-perspective-dragon-4-5",
    source: "perspective-dragon-4",
    target: "perspective-dragon-5",
    sourceHandle: "perspective-next",
    targetHandle: "perspective-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-alfred-1-perspective-alfred-1",
    source: "character-alfred-1",
    target: "perspective-alfred-1",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-alfred-2-perspective-alfred-2",
    source: "character-alfred-2",
    target: "perspective-alfred-2",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-alfred-3-perspective-alfred-3",
    source: "character-alfred-3",
    target: "perspective-alfred-3",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-alfred-5-perspective-alfred-5",
    source: "character-alfred-5",
    target: "perspective-alfred-5",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-dragon-2-perspective-dragon-2",
    source: "character-dragon-2",
    target: "perspective-dragon-2",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-dragon-4-perspective-dragon-4",
    source: "character-dragon-4",
    target: "perspective-dragon-4",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-character-dragon-5-perspective-dragon-5",
    source: "character-dragon-5",
    target: "perspective-dragon-5",
    sourceHandle: "perspective",
    targetHandle: "character",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-narrative-1-2",
    source: "narrative-1",
    target: "narrative-2",
    sourceHandle: "narrative-next",
    targetHandle: "narrative-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-narrative-2-3",
    source: "narrative-2",
    target: "narrative-3",
    sourceHandle: "narrative-next",
    targetHandle: "narrative-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-narrative-3-4",
    source: "narrative-3",
    target: "narrative-4",
    sourceHandle: "narrative-next",
    targetHandle: "narrative-prev",
    type: "customEdge",
    animated: true,
  },
  {
    id: "edge-narrative-4-5",
    source: "narrative-4",
    target: "narrative-5",
    sourceHandle: "narrative-next",
    targetHandle: "narrative-prev",
    type: "customEdge",
    animated: true,
  },
];
